// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OtroRegistroConDetalle.DAL;

namespace OtroRegistroConDetalle.Migrations
{
    [DbContext(typeof(Contexto))]
    [Migration("20210622003933_inicial")]
    partial class inicial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.7");

            modelBuilder.Entity("OtroRegistroConDetalle.Models.Ordenes", b =>
                {
                    b.Property<int>("ordenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("fecha")
                        .HasColumnType("TEXT");

                    b.Property<float>("monto")
                        .HasColumnType("REAL");

                    b.Property<int>("suplidorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("ordenId");

                    b.ToTable("Ordenes");
                });

            modelBuilder.Entity("OtroRegistroConDetalle.Models.OrdenesDetalle", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("cantidad")
                        .HasColumnType("REAL");

                    b.Property<float>("costo")
                        .HasColumnType("REAL");

                    b.Property<int>("ordenId")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.HasIndex("ordenId");

                    b.ToTable("OrdenesDetalle");
                });

            modelBuilder.Entity("OtroRegistroConDetalle.Models.Productos", b =>
                {
                    b.Property<int>("productoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("costo")
                        .HasColumnType("REAL");

                    b.Property<string>("descripcion")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("inventario")
                        .HasColumnType("REAL");

                    b.HasKey("productoId");

                    b.ToTable("Productos");

                    b.HasData(
                        new
                        {
                            productoId = 1,
                            costo = 20f,
                            descripcion = "Arroz Jose Jose",
                            inventario = 1000f
                        },
                        new
                        {
                            productoId = 2,
                            costo = 120.5f,
                            descripcion = "Carne Molida",
                            inventario = 500.25f
                        },
                        new
                        {
                            productoId = 3,
                            costo = 50f,
                            descripcion = "Manzanas rojas",
                            inventario = 100f
                        },
                        new
                        {
                            productoId = 4,
                            costo = 400f,
                            descripcion = "Salami Induveca",
                            inventario = 203f
                        });
                });

            modelBuilder.Entity("OtroRegistroConDetalle.Models.Suplidores", b =>
                {
                    b.Property<int>("suplidorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("nombre")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("suplidorId");

                    b.ToTable("Suplidores");

                    b.HasData(
                        new
                        {
                            suplidorId = 1,
                            nombre = "Jose Carlos"
                        },
                        new
                        {
                            suplidorId = 2,
                            nombre = "Carmen Maria"
                        },
                        new
                        {
                            suplidorId = 3,
                            nombre = "Ana Patria"
                        },
                        new
                        {
                            suplidorId = 4,
                            nombre = "Andres Jesus"
                        });
                });

            modelBuilder.Entity("OtroRegistroConDetalle.Models.OrdenesDetalle", b =>
                {
                    b.HasOne("OtroRegistroConDetalle.Models.Ordenes", null)
                        .WithMany("OrdenesDetalle")
                        .HasForeignKey("ordenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("OtroRegistroConDetalle.Models.Ordenes", b =>
                {
                    b.Navigation("OrdenesDetalle");
                });
#pragma warning restore 612, 618
        }
    }
}
